### ISSUE TITLE
部分论文分类错误？

### ISSUE THREAD

**Issue by TangJiakai** [CHIANGEL/Awesome-LLM-for-RecSys#10]
感觉一些论文分类并不太符合原Survey的要求？
比如UP5，POD，BDLM等等

**Comment by CHIANGEL** [comment]
感谢您的交流和指点，我重新check了这三篇论文：

首先三篇论文我认为都属于Scoring/Ranking Function大类，因为LLM的目的都是完成推荐任务（预测分数或者生成物品），BDLM是额外引入了传统推荐模型，但LLM的作用仍然会涉及到打分或生成（即$loss_{LLM}$）

在细分类上：
- UP5确实分类错误，他应该属于Item Generation Task而非Item Scoring Task
- POD没有分类错误，它的任务包含了序列推荐和Top-N推荐（和UP5一致），所以是属于Item Generation
- BDLM没有分类错误，它的任务在原文Table 2中有展示，同时包含预估分数和生成物品，所以属于Hybrid

再次感谢您的意见，如果我的阐述有误以及关于repo中的其他分类问题，欢迎进一步交流。

BTW我们的更新版本的survey已经提交Arxiv，预计下周一公开：）

**Comment by TangJiakai** [comment]
1. survey对于Hybrid Task的定义好像只要是不止一个任务就都算，那么UP5似乎也应该归类到Hybrid？（因为原文是包括序列和直接推荐）
2. POD同上，而且POD是对P5的小改动，那应该也是要和P5都算Hybrid
3. BDLM的话，LLM方也包含两个任务（interaction prediction和TopN推荐），那么还是可以归到Hybrid；而从实验效果来看，基于传统推荐模型效果更好，从这个角度来看，分到Feature Encoding 也能说得通。

不过我觉得追求这么细，意义好像不大哈哈。期待新survey！

**Comment by CHIANGEL** [comment]
这个可能是我们原版survey写作上的问题，导致了您对Hybrid Task的误解。

我们对Hybrid的定义是要同时包含Item Scoring和Item Generation才算，比如POD是采用了P5的序列推荐和Top-N推荐两个任务，这两个任务其实是Item Generation下面细分。而P5算hybrid是因为它还多了一个Rating Prediction Task。

在我们的新版survye里我们为Scoring和Generation做了进一步的细分。比如Generaion可以根据是否需要在Prompt中提供Candidate Items细分为开集物品生成（Open-set Generation）和闭集物品生成（Closed-set Generation）。POD的序列推荐对应了开集生成（给序列，生成下一个item），Top-N则对应了闭集生成（给候选集，生成选择的那个item）。

对于BDLM，其实有一些工作的定位就是会比较模糊，在新版survey里我们也强调很多新工作是可以同时被归类到多个pipeline stage的，毕竟LLM确实有这个能力嘛哈哈哈。

在Survey上有细致的讨论是很好的事情，很高兴可以和您聊这么多~再次感谢您的交流和支持

**Comment by TangJiakai** [comment]
原来如此，确实误解了原文意思哈，感谢您的耐心回复！
