### ISSUE TITLE
Could you update two highly related datasets?

### ISSUE THREAD

**Issue by yxin98** [CHIANGEL/Awesome-LLM-for-RecSys#11]
Dear authors, thanks for your great contribution to the recommender system community! Could you add two more datasets to make the GitHub page more comprehensive?

Ninerec, the RS-scenario is Feeds, and the link is https://github.com/westlake-repl/NineRec. It provides multiple datasets with raw text and images for transfer learning in recommender systems

MicroLens, the RS-scenario is Video Streaming, and the link is https://github.com/westlake-repl/MicroLens. It provides a large-scale short video dataset for recommendation tasks, providing various original modal content including text, images, audio, and videos.

**Comment by CHIANGEL** [comment]
YEAH! Big thanks for your dataset requests. The two datasets have been added to the repo now. Feel free to keep in touch and communicate. : )
