### ISSUE TITLE
Request for adding one dataset paper 

### ISSUE THREAD

**Issue by ChandlerBang** [CHIANGEL/Awesome-LLM-for-RecSys#2]
Dear Repo Owner,

Thank you for maintaining this nice repo of LLM for Recommendation. We have recently released a session-recommendation dataset named [Amazon-M2](https://arxiv.org/abs/2307.09688) for evaluating LLMs in recommendation scenarios. It provides both a dataset, a benchmark, and three text-related tasks. Would you mind adding this work to your repo?

Thank you for your attention.

**Comment by CHIANGEL** [comment]
Hi, 

Big thanks for your request to remind us about this awesome dataset and benchmark. We have added it to our repo. 

Please feel free to send us more information or other related resources if needed.

Best Regards.

**Comment by ChandlerBang** [comment]
Thank you!
