### ISSUE TITLE
A Request to Include a Paper on Conversational Recommendations with LLMs

### ISSUE THREAD

**Issue by AaronHeee** [CHIANGEL/Awesome-LLM-for-RecSys#4]
Hi @CHIANGEL,

Thanks so much for sharing such a nice repo on LLMs for Rec. I am wondering if our recent paper [Large Language Models as Zero-Shot Conversational Recommenders](https://github.com/AaronHeee/LLMs-as-Zero-Shot-Conversational-RecSys) could be included in this list?

Our contributions include (1) datasets: new conversational recommendation datasets from Reddit; (2) LLMs evaluation on conversational recommendation tasks and related analysis. 

Thanks in advance!

**Comment by AaronHeee** [comment]
Oh I saw the paper in the pending list, sorry. Not sure if the datasets could be included in the dataset list?

**Comment by CHIANGEL** [comment]
Hi

Big thanks for your request about the new conversational dataset. We have added it to our repo.

Please feel free to send us more information or other related resources if needed.

Best Regards.

**Comment by AaronHeee** [comment]
Thanks a lot!
