### ISSUE TITLE
Recommending a new paper relevant to the "1.2 LLM as Feature Encoder" section

### ISSUE THREAD

**Issue by gimpong** [CHIANGEL/Awesome-LLM-for-RecSys#6]
Hi Jianghao,

Thanks for your awesome repository and the excellent survey! I believe both of them will help many researchers gain insights into the latest LLM-related techniques and bring long-term benefits to the RS community.

I am happy to announce our paper, "MISSRec: Pre-training and Transferring Multi-modal Interest-aware Sequence Representation for Recommendation" (https://arxiv.org/abs/2308.11175), on ACM MM 2023. This paper is about integrating multi-modal information (using the pre-trained and frozen CLIP-ViT-B/32 model) into behavior sequence representation to support universal recommendation. The data and code are also available at https://github.com/gimpong/MM23-MISSRec.

If the paper falls within the scope of this repository, I would appreciate it if you considered including it in the paper list. :)

Kind regards,
Jinpeng

**Comment by CHIANGEL** [comment]
Hi Jinpeng,

Thanks for recognizing our work and efforts. Also big thanks for reminding me of such an awesome job on multi-modal recommendation. I have appended the paper in Section 1.6 pending list. Our new version of survey is upcoming probably next month. The paper will then be included in Section 1.2.

Please feel free to contact for any problems.

Best
Jianghao
